export const NODEREGISTRY_PROCESS_ID = "lsVh9GO7pzFXcFEuAfw7l_9WU7KAAqTRkU0kVH0lx2g";
export const DATAREGISTRY_PROCESS_ID = "daYyE-QRXg2MBrX1E1lUmJ1hMR-GEmyrdUiUnv3dWLY";
export const TASKS_PROCESS_ID = "fX6ek4jPhcpM0XIOw2CNO2xiOUYGPuaRHXztW9_JWsY";